[package]
name = "frontest"
version = "0.3.0"
edition = "2021"
authors = ["Maciej Zwoliński <mac.zwolinski@gmail.com>"]
repository = "https://github.com/zwo1in/frontest-rs"
homepage = "https://github.com/zwo1in/frontest-rs"
documentation = "https://docs.rs/frontest"
license = "MIT OR Apache-2.0"
keywords = ["web", "wasm", "dom", "test", "frontend"]
categories = [
  "wasm",
  "web-programming",
  "accessibility",
  "development-tools::testing",
]
description = "A crate for querying, matching and asserting DOM"
readme = "README.md"

[features]
default = ["yew"]

[dependencies]
gloo = { version = "0.11", features = ["futures"] }
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3", features = [
  "Document",
  "Element",
  "HtmlElement",
  "HtmlCollection",
  "HtmlInputElement",
  "HtmlLabelElement",
  "HtmlButtonElement",
  "HtmlMeterElement",
  "HtmlOutputElement",
  "HtmlProgressElement",
  "HtmlSelectElement",
  "HtmlTextAreaElement",
  "Node",
  "NodeList",
] }

yew = { version = "0.21", optional = true, features = ["csr"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
futures = "0.3"
